# Site settings
title: Istiyak H. Siddiquee
description: 'Intro Page'
url: 'https://www.linkedin.com/in/istiyaksiddiquee/'
baseurl: 'https://www.linkedin.com/in/istiyaksiddiquee/'
profilepic: '/images/siddiquee.jpg'
bkimage: '/images/cover.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'c427e96267.js'

author:
  name: 'Istiyak H. Siddiquee'
  email: istiyaksiddiquee@gmail.com
  twitter_username: istiyaksiddique
  facebook_username: istiyaksiddiquee
  github_username:  istiyaksiddiquee
  linkedin_username:  istiyaksiddiquee
  cv: https://github.com/istiyaksiddiquee/istiyaksiddiquee.github.io/raw/master/resources/Mohammad%20Istiyak%20Hossain%20Siddiquee%2004Oct2020.pdf

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
